config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}

  root "static_pages#show", page: "home"
  get "/pages/:page" => "static_pages#show"

  namespace :admin do
    root "static_pages#show", page: "dashboard"
    get "/pages/:page" => "static_pages#show"

    resources :users, except: %i(show edit)
    resources :borrows
    resources :authors do
      resources :books
    end
    resources :books do
      resources :book_items
    end
    resources :categories, except: %i(show edit)
    resources :publishers do
      resources :books
    end
  end

  resources :books, only: %i(index show) do
    resources :comments, only: %i(create destroy) do
      resources :votes, only: %i(create destroy)
    end
    resource :suggest_books, only: :create
    resource :rate, only: :create
    resources :book_marks, only: %i(create destroy)
  end
  resources :search, only: :index
  resources :users, only: :show
  resources :categories, only: %i(index show)
  resources :borrows, only: %i(create update)
  resources :explorer, only: :index
  resources :tags, only: %i(index show)

  namespace :blog do
    root "dashboard#index"
    resources :posts, only: %i(index show create edit update destroy) do
      resources :comments, only: %i(create destroy) do
        resources :votes, only: %i(create destroy)
      end
    end
  end
  resources :read_online, only: :show
  resources :authors, only: :show
  resources :announcements, only: %i(index show)
  resources :not_found, only: :index
  resources :requests, only: %i(index create update)
  resources :notifications, only: %i(index update)
  patch "/make_all_as_read" => "make_all_as_read#update"
  resources :feedback, only: %i(index new create show update)

  mount ActionCable.server => "/cable"
  resources :messages
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < AdminController
  def show
    if valid_page?
      render "admin/static_pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private

  def valid_page?
    File.exist? Pathname.new(Rails.root +
      "app/views/admin/static_pages/#{params[:page]}.html.erb")
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include ApplicationHelper

  def show
    setting = Settings.user.home
    @support = Supports::Home.new popular_book:
      Book.popular_book(setting.popular_book),
      recent_blog: Blog.recent_blog(setting.recent_blog),
      top_author: Author.top_author,
      top_rate_book: Book.top_rated_book(setting.top_rate_book),
      last_15_book: Book.last_15_book

    if valid_page?
      render "static_pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private

  def valid_page?
    File.exist? Pathname.new(Rails.root +
      "app/views/static_pages/#{params[:page]}.html.erb")
  end
end

app/views/static_pages/_book_slide_item.html.erb
<div class="book-grid" >
  <div class="book-item-info pmd-z-depth-1">
    <p class="book-title" title="<%= b.title %>">
      <%= link_to b.title.truncate(
        Settings.user.home.truncate.item_book_title), book_path(b),
        "data-turbolinks": false %></p>
    <div class="star-in-item">
      <% (1..(load_rate b.rate).first).each do %>
        <i class="fa fa-star" aria-hidden="true"></i>
      <% end  %>
      <% (1..(load_rate b.rate).second).each do %>
        <i class="fa fa-star-half-o" aria-hidden="true"></i>
      <% end  %>
      <% (1..(load_rate b.rate).last).each do %>
        <i class="fa fa-star-o" aria-hidden="true"></i>
      <% end  %>
    </div>
    <p class="book-author">
      <% b.authors.each_with_index do |a, index| %>
        <% if index == b.authors.count - 1 %>
          <%= link_to a.name, a, "data-turbolinks": false %>
        <% else %>
          <%= link_to a.name, a, "data-turbolinks": false %>,
        <% end %>
      <% end %>
    </p>
    <p class="book-category">
      <% if b.categories.present? %>
        <%= link_to b.categories.first.title, b.categories.first,
          "data-turbolinks": false %></p>
      <% end %>
    </p>
  </div>
  <img src="<%= b.images.first.url.thumb %>"
    class="img-responsive">
  <% if b.new_book? %>
    <div class="new-tag">
      <%= t "books.show.new_tag" %>
    </div>
  <% end %>
</div>

app/views/static_pages/_hot_author.html.erb
<div class="container">
  <div class="row title-heading">
    <h2 class="row-title"><%= t "user.home.top_author" %></h2>
  </div>
  <div class="slide-nav author-slide">
    <i class="fa fa-angle-left fa-2x" aria-hidden="true"></i>
    <i class="fa fa-angle-right fa-2x" aria-hidden="true"></i>
  </div>
  <div class="owl-carousel owl-theme" id="author-slide">
    <% support.load_top_author.each do |author| %>
      <div class="row">
        <div class="col-sm-6 col-sm-offset-1 book-info-container">
          <h2><%= link_to author.name, author,
            "data-turbolinks": false %></h2>
          <% if author.description.present? %>
            <p title="<%= author.description %>">
              <%= author.description.truncate(
                Settings.user.home.truncate.author_description) %>
            </p>
          <% end %>
          <div class="owl-carousel owl-theme book-of-author-slide
            author-book-slide">
            <% author.books.each do |b| %>
              <div class="book-grid" >
                <div class="book-item-info">
                  <p class="book-title" title="<%= b.title %>">
                    <%= link_to b.title.truncate(Settings.user.home.truncate.item_book_title),
                      b, "data-turbolinks": false %>
                  </p>
                  <div class="star-in-item">
                    <% (1..(load_rate b.rate).first).each do %>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    <% end  %>
                    <% (1..(load_rate b.rate).second).each do %>
                      <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <% end  %>
                    <% (1..(load_rate b.rate).last).each do %>
                      <i class="fa fa-star-o" aria-hidden="true"></i>
                    <% end  %>
                  </div>
                  <p class="book-author">
                    <% b.authors.each_with_index do |a, index| %>
                      <% if index == b.authors.count - 1 %>
                        <%= link_to a.name, a,
                          "data-turbolinks": false %>
                      <% else %>
                        <%= link_to a.name, a,
                          "data-turbolinks": false %>,
                      <% end %>
                    <% end %>
                  </p>
                  <p class="book-category">
                    <%= link_to b.categories.first.title,
                      b.categories.first,
                      "data-turbolinks": false %>
                  </p>
                </div>
                <img src="<%= b.images.first.try(:url).try(:thumb).try(:url) %>"
                  class="img-responsive pmd-z-depth-1">
                <% if b.new_book? %>
                  <div class="new-tag"><%= t "books.show.new_tag" %></div>
                <% end %>
              </div>
            <% end %>
            <div class="book-shelf"></div>
          </div>
        </div>
        <div class="col-sm-3 img-container col-sm-offset-1">
          <img src="<%= author.avatar.try :url %>"
            class="img-responsive author-img">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/static_pages/_hot_book.html.erb
<div class="container">
  <div class="row title-heading">
    <h2 class="row-title"><%= t "user.home.new_book" %></h2>
  </div>
  <div class="slide-nav book-slide">
    <i class="fa fa-angle-left fa-2x" aria-hidden="true"></i>
    <i class="fa fa-angle-right fa-2x" aria-hidden="true"></i>
  </div>
  <div class="owl-carousel owl-theme" id="new-book-slide">
    <% support.load_new_book.each do |book| %>
      <div class="row">
        <div class="col-sm-3 col-sm-offset-1 img-container">
          <%= link_to book_path(book), "data-turbolinks": false do %>
            <img src="<%= book.images.first.url %>"
              class="img-responsive">
          <% end %>
        </div>
        <div class="col-sm-6 col-sm-offset-1 book-info-container">
          <h2><%= link_to book.title, book,
            "data-turbolinks": false %></h2>
          <h4>
            <% book.authors.each_with_index do |a, index| %>
              <% if index == book.authors.count - 1 %>
                <%= link_to a.name, a, "data-turbolinks": false %>
              <% else %>
                <%= link_to a.name, a, "data-turbolinks": false %>,
              <% end %>
            <% end %>
          </h4>
          <p title="<%= book.description %>">
            <%= book.description.truncate(Settings.user.home.truncate.book_description) %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="home-page static-pages">
  <div class="hero-home">
    <div class="container">
      <div class="owl-carousel owl-theme" id="hero-slide">
        <div class="slide1">
          <p class="home-slide-title-1 enjoy-css">
            <%= t "user.home.slide.slide1_title1" %>
          </p>
          <p class="home-slide-title-2">
            <%= t "user.home.slide.slide1_title2" %>
          </p>
          <i class="fa fa-angle-up" aria-hidden="true"></i>
          <i class="fa fa-angle-down" aria-hidden="true"></i>
        </div>
        <div>
          <p class="home-slide-title-2">
            <%= t "user.home.slide.slide2_title2" %>
          </p>
          <p class="home-slide-title-1">
            <%= t "user.home.slide.slide2_title1" %>
          </p>
          <i class="fa fa-angle-up" aria-hidden="true"></i>
          <i class="fa fa-angle-down" aria-hidden="true"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="home-body container">
    <div class="row">
      <div class="col-sm-3 home-guide-box">
        <h2><%= t "user.home.guide.books" %></h2>
        <p><%= t "user.home.guide.books_content" %></p>
        <p><%= link_to t("user.home.guide.start_explore"), explorer_index_path,
          "data-turbolinks": false %></p>
      </div>
      <div class="col-sm-3 home-guide-box">
        <h2 class="heading-bottom">
          <%= t "user.home.guide.blogs" %>
        </h2>
        <p class="paragraph-bottom">
          <%= t "user.home.guide.blog_content" %>
        </p>
        <p><%= link_to t("user.home.guide.start_explore"), blog_root_path,
          "data-turbolinks": false %></p>
      </div>
      <div class="col-sm-3 home-guide-box">
        <h2><%= t "user.home.guide.borrow" %></h2>
        <p><%= t "user.home.guide.borrow_content" %></p>
        <p><%= link_to t("user.home.guide.choose_book"), categories_path,
          "data-turbolinks": false %></p>
      </div>
      <div class="col-sm-3 home-guide-box">
        <h2 class="heading-bottom">
          <%= t "user.home.guide.feedback" %>
        </h2>
        <p class="paragraph-bottom">
          <%= t "user.home.guide.feedback_content" %>
        </p>
        <p><%= link_to t("user.home.guide.feedback_link"), "",
          class: "btn-feedback-home", "data-target": "#complete-dialog",
          "data-toggle": "modal", "data-turbolinks": false %></p>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid recommend-book">
  <div class="container">
    <div class="col-sm-12 text-center title-heading">
      <h2><%= t "user.home.recommend" %></h2>
      <p><%= t "user.home.recommend_details" %></p>
    </div>
    <div class="col-sm-12 bookshelf">
      <div class="col-sm-10 col-sm-offset-1 slider">
        <div class="slide-nav">
          <i class="fa fa-angle-left fa-3x" aria-hidden="true"></i>
          <i class="fa fa-angle-right fa-3x" aria-hidden="true"></i>
        </div>
        <div class="owl-carousel owl-theme recommend-book-slider"
          id="recommended-book-slide">
          <% if @support.load_top_rate_book.present? %>
            <% @support.load_top_rate_book.each do |book| %>
              <%= render "book_slide_item", b: book %>
            <% end %>
          <% else %>
            <% @support.load_new_book.each do |book| %>
              <%= render "book_slide_item", b: book %>
            <% end %>
          <% end %>
          <div class="book-shelf"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid hot-book">
  <%= render "hot_book", support: @support %>
</div>

<div class="container-fluid hot-author">
  <%= render "hot_author", support: @support %>
</div>