config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}

  root "static_pages#show", page: "home"
  get "/pages/:page" => "static_pages#show"

  namespace :admin do
    root "static_pages#show", page: "dashboard"
    get "/pages/:page" => "static_pages#show"

    resources :users, except: %i(show edit)
    resources :borrows
    resources :authors do
      resources :books
    end
    resources :books do
      resources :book_items
    end
    resources :categories, except: %i(show edit)
    resources :publishers do
      resources :books
    end
  end

  resources :books, only: %i(index show) do
    resources :comments, only: %i(create destroy) do
      resources :votes, only: %i(create destroy)
    end
    resource :suggest_books, only: :create
    resource :rate, only: :create
    resources :book_marks, only: %i(create destroy)
  end
  resources :search, only: :index
  resources :users, only: :show
  resources :categories, only: %i(index show)
  resources :borrows, only: %i(create update)
  resources :explorer, only: :index
  resources :tags, only: %i(index show)

  namespace :blog do
    root "dashboard#index"
    resources :posts, only: %i(index show create edit update destroy) do
      resources :comments, only: %i(create destroy) do
        resources :votes, only: %i(create destroy)
      end
    end
  end
  resources :read_online, only: :show
  resources :authors, only: :show
  resources :announcements, only: %i(index show)
  resources :not_found, only: :index
  resources :requests, only: %i(index create update)
  resources :notifications, only: %i(index update)
  patch "/make_all_as_read" => "make_all_as_read#update"
  resources :feedback, only: %i(index new create show update)

  mount ActionCable.server => "/cable"
  resources :messages
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :find_notification, only: :update

  def index
    @notifications = current_user.notifications.order(id: :desc)
      .page(params[:page])
      .per Settings.notifications.per_page
  end

  def update
    @notify.update_attributes read: true
    render json: {unread: unread_notifications_count}
  end

  private

  def find_notification
    @notify = current_user.notifications.find_by id: params[:id]
  end

  def unread_notifications_count
    current_user.notifications.where(read: false).size
  end
end

app/views/notifications/index.html.erb
<% provide :title, t("notifications.index.notifications") %>
<div class="container noti-wrapper">
  <div class="row">
    <% if unread_notifications_count == 0 %>
      <div class="col-sm-12 text-center">
        <div class="alert alert-success">
          <strong class="fa fa-fw fa-bell-slash-o"></strong>
          <%= t "notifications.index.dont_have_notification" %>
        </div>
      </div>
    <% else %>
      <div class="col-sm-12 text-center">
        <div class="alert alert-info">
          <strong class="fa fa-fw fa-bell-o"></strong>
          <%= t "notifications.index.you_have_notification",
            count: unread_notifications_count %>
        </div>
      </div>
    <% end %>
    <div class="col-sm-12 noti-header">
      <h1 class="text-uppercase">
        <%= t "notifications.index.your_notifications" %>
        <%= link_to t(".make_all_read"), make_all_as_read_path, method: :patch,
          class: "pull-right btn btn-sm btn-primary pmd-btn-raised" %>
      </h1><hr>
    </div>
    <div class="col-sm-12 noti">
      <% @notifications.each do |notification| %>
        <div class="list-group">
          <span class="list-group-item">
            <h4 class="list-group-item-heading">
              <%= notification.content.html_safe %>
              <% unless notification.read? %>
                <span class="pull-right unread fa fa-circle text-success"
                  title="Unread"></span>
              <% end %>
            </h4>
            <p class="list-group-item-text">
              <%= time_ago_in_words notification.created_at %>
            </p>
          </span>
        </div><hr>
      <% end %>
    </div>
    <div class="col-sm-12">
      <%= paginate @notifications, theme: "twitter-bootstrap-3" %>
    </div>
  </div>
</div>