config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}

  root "static_pages#show", page: "home"
  get "/pages/:page" => "static_pages#show"

  namespace :admin do
    root "static_pages#show", page: "dashboard"
    get "/pages/:page" => "static_pages#show"

    resources :users, except: %i(show edit)
    resources :borrows
    resources :authors do
      resources :books
    end
    resources :books do
      resources :book_items
    end
    resources :categories, except: %i(show edit)
    resources :publishers do
      resources :books
    end
  end

  resources :books, only: %i(index show) do
    resources :comments, only: %i(create destroy) do
      resources :votes, only: %i(create destroy)
    end
    resource :suggest_books, only: :create
    resource :rate, only: :create
    resources :book_marks, only: %i(create destroy)
  end
  resources :search, only: :index
  resources :users, only: :show
  resources :categories, only: %i(index show)
  resources :borrows, only: %i(create update)
  resources :explorer, only: :index
  resources :tags, only: %i(index show)

  namespace :blog do
    root "dashboard#index"
    resources :posts, only: %i(index show create edit update destroy) do
      resources :comments, only: %i(create destroy) do
        resources :votes, only: %i(create destroy)
      end
    end
  end
  resources :read_online, only: :show
  resources :authors, only: :show
  resources :announcements, only: %i(index show)
  resources :not_found, only: :index
  resources :requests, only: %i(index create update)
  resources :notifications, only: %i(index update)
  patch "/make_all_as_read" => "make_all_as_read#update"
  resources :feedback, only: %i(index new create show update)

  mount ActionCable.server => "/cable"
  resources :messages
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :books, join_table: :book_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_tag, only: :show
  before_action :sort_params, only: %i(index show)
  before_action :load_tags, only: :show

  def index
    @tags = Tag.page(params[:page])
      .per Settings.explorer.tags.limit
  end

  def show
    @books = @tag.books.order("#{params[:sort]}": :desc)
      .page(params[:page])
      .per Settings.categories.category.limit
  end

  private

  def find_tag
    @tag = Tag.friendly.find(params[:id])

    return if @tag
    redirect_to tags_path
  end

  def load_tags
    @tags = Tag.all.limit Settings.explorer.tags.limit
  end

  def sort_params
    param! :sort, String,
      in: %w(title created_at public_date),
      transform: :downcase, default: "created_at"
  end
end

app/views/tags/index.html.erb
<% provide :title, t("tags.index.explorer_tags") %>
<div class="container-fluid header-block-no-border">
  <h1 class="text-capitalize"><%= t "tags.index.explorer_tags" %></h1>
</div>
<div class="container" id="tags-show">
  <div class="row">
    <div class="col-sm-12 tags">
      <% @tags.each do |tag| %>
        <%= link_to tag, "data-turbolinks": false do %>
          <div class="pmd-chip pmd-chip-no-icon">
            <%= tag.title %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<% provide :title, @tag.title %>
<div class="container-fluid header-block">
  <h2><%= t "tags.show.tag" %></h2>
  <h1 class="text-capitalize"><%= @tag.title %></h1>
</div>
<div class="container" id="tags-show">
  <div class="row">
    <div class="col-sm-3">
      <div class="row">
        <div class="col-sm-12">
          <h2 class="text-uppercase">
            <%= t "search.index.tag_suggestions" %>
            <%= link_to t("explorer.index.see_all"), tags_path,
              "data-turbolinks": false, class: "pull-right text-capitalize" %>
          </h2>
        </div>
        <div class="col-sm-12 tags">
          <% @tags.each do |tag| %>
            <%= link_to tag, "data-turbolinks": false do %>
              <div class="pmd-chip pmd-chip-no-icon">
                <%= tag.title %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-9 tab-style-1-content">
      <div class="row">
        <div class="col-sm-12">
          <div class="row category-header">
            <div class="col-sm-9">
              <h2><%= t "categories.show.collection" %></h2>
            </div>
            <div class="col-sm-3">
              <%= form_with url: tag_path(@tag), method: :get,
                local: true, id: "form" do |f| %>
                <%= f.select :sort, books_sort_params,
                  {selected: params[:sort]}, {class: "form-control", id: "sort"} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <% @books.each do |book| %>
          <%= render "categories/book", book: book %>
        <% end %>
      </div>
      <div class="row">
        <div class="col-sm-9">
          <hr>
          <%= paginate @books, theme: "twitter-bootstrap-3" %>
        </div>
      </div>
    </div>
  </div>
</div>