config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}

  root "static_pages#show", page: "home"
  get "/pages/:page" => "static_pages#show"

  namespace :admin do
    root "static_pages#show", page: "dashboard"
    get "/pages/:page" => "static_pages#show"

    resources :users, except: %i(show edit)
    resources :borrows
    resources :authors do
      resources :books
    end
    resources :books do
      resources :book_items
    end
    resources :categories, except: %i(show edit)
    resources :publishers do
      resources :books
    end
  end

  resources :books, only: %i(index show) do
    resources :comments, only: %i(create destroy) do
      resources :votes, only: %i(create destroy)
    end
    resource :suggest_books, only: :create
    resource :rate, only: :create
    resources :book_marks, only: %i(create destroy)
  end
  resources :search, only: :index
  resources :users, only: :show
  resources :categories, only: %i(index show)
  resources :borrows, only: %i(create update)
  resources :explorer, only: :index
  resources :tags, only: %i(index show)

  namespace :blog do
    root "dashboard#index"
    resources :posts, only: %i(index show create edit update destroy) do
      resources :comments, only: %i(create destroy) do
        resources :votes, only: %i(create destroy)
      end
    end
  end
  resources :read_online, only: :show
  resources :authors, only: :show
  resources :announcements, only: %i(index show)
  resources :not_found, only: :index
  resources :requests, only: %i(index create update)
  resources :notifications, only: %i(index update)
  patch "/make_all_as_read" => "make_all_as_read#update"
  resources :feedback, only: %i(index new create show update)

  mount ActionCable.server => "/cable"
  resources :messages
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :parent_category, class_name: Category.name,
    foreign_key: :parent_id, optional: true
  has_many :book_categories
  has_many :books, through: :book_categories, dependent: :destroy
  has_many :child_categories, class_name: Category.name,
    foreign_key: :parent_id

  mount_uploader :image, CategoryUploader

  scope :group_categories, ->{where parent_id: nil}

  def total_books
    if self.parent_category
      self.book_categories.size
    else
      categories_total_books
    end
  end

  private

  def categories_total_books
    count = 0
    child_categories.joins(:books)
      .select("categories.id, categories.title, count(books.id) as count")
      .group("categories.id")
      .map{|c| count += c.count}
  end
end

app/controllers/admin/categories_controller.rb
class Admin
  class CategoriesController < AdminController
    skip_before_action :verify_authenticity_token
    before_action :find_category, only: %i(update destroy)

    def index
      @data = Supports::AdminCategories.new categories: Category.all,
        param: params, books: Book.all
      @category = Category.new
    end

    def create
      category = Category.new category_params
      if category.save
        flash[:success] = t "admin.categories.create.success"
      else
        flash[:danger] = t "admin.categories.create.something_wrong"
      end
    end

    def update
      if @category.update_attributes category_params
        flash[:success] = t "admin.categories.update.success"
      else
        flash[:danger] = t "admin.categories.update.something_wrong"
      end
    end

    def destroy
      if @category.destroy
        flash[:success] = t "admin.categories.destroy.success"
      else
        flash[:danger] = t "admin.categories.destroy.something_wrong"
      end
    end

    private

    def find_category
      @category = Category.friendly.find(params[:id])

      return if @category
      flash[:danger] = t "admin.categories.index.not_exist"
    end

    def category_params
      params.require(:category).permit :title, :description, :image,
        :parent_id, book_ids: []
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: :show
  before_action :sort_params, only: %i(index show)
  before_action :load_categories, only: %i(index show)

  def index
    @books = Book.order("#{params[:sort]}": :desc).page(params[:page])
      .per Settings.categories.category.limit
  end

  def show
    @books = @category.books.order("#{params[:sort]}": :desc)
      .page(params[:page])
      .per Settings.categories.category.limit
  end

  private

  def find_category
    @category = Category.friendly.find(params[:id])

    return if @category
    redirect_to not_found_index_path
  end

  def load_categories
    @categories = Category.group_categories
  end

  def sort_params
    param! :sort, String,
      in: %w(title created_at public_date),
      transform: :downcase, default: "created_at"
  end
end

app/views/categories/_book.html.erb
<div class="col-sm-4">
  <div class="box-outer">
    <div class="box">
      <div class="frame">
        <div class="caption">
        </div>
        <div class="img-frame">
          <%= link_to book, "data-turbolinks": false do %>
            <% if book.images.first.present? %>
              <img src="<%= book.images.first.url.thumb.url %>"
                class="img-responsive" alt="<%= book.title %>">
            <% else %>
              <img src="<%= asset_path "default-book.png" %>"
                class="img-responsive" alt="<%= book.title %>">
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="text-column">
        <span>
          <% book.categories.each do |category| %>
            <%= link_to category.title, category, "data-turbolinks": false %>
            <%= category != book.categories.last ? ", " : nil %>
          <% end %>
        </span>
        <h3>
          <%= link_to book.title.truncate(Settings.truncate.book.title),
            book, "data-turbolinks": false %>
        </h3>
        <em><%= book.description.truncate Settings.truncate.book.desc %></em>
        <div class="review-start">
          <div class="rating_stars">
            <div class="rating_down">
              <div class="rating_up" style="width:100%;"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_sidebar.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2 class="text-uppercase">
      <%= t "explorer.index.categories" %>
      <%= link_to t("explorer.index.see_all"), categories_path,
        class: "pull-right text-capitalize" %>
    </h2>
  </div>
  <div class="col-sm-12 side-menu">
    <div class="side-menu-container">
      <ul class="nav navbar-nav">
        <% categories.each do |category| %>
          <% if category.child_categories.present? %>
            <li class="panel panel-default" id="dropdown">
              <a data-toggle="collapse" href="#dropdown-lvl<%= category.id %>"
                data-turbolinks="false">
                <%= category.title %>
                <span class="badge"><%= category.total_books %></span>
                <i class="caret"></i>
              </a>
              <div id="dropdown-lvl<%= category.id %>" class="panel-collapse collapse">
                <div class="panel-body">
                  <ul class="nav navbar-nav">
                    <% category.child_categories.each do |child_category| %>
                      <li>
                        <%= link_to child_category, "data-turbolinks": false do %>
                          <%= child_category.title %>
                          <span class="badge">
                            <%= child_category.books.size %>
                          </span>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </li>
          <% else %>
            <li>
              <%= link_to category, "data-turbolinks": false do %>
                <%= category.title %>
                <span class="badge"><%= category.books.size %></span>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<% provide :title, t("categories.index.all_categories") %>
<div class="container-fluid header-block-no-border">
  <h1 class="text-capitalize">
    <%= t "categories.index.all_categories" %>
  </h1>
</div>
<div class="container" data-turbolinks="false">
  <div class="row">
    <div class="col-sm-3">
      <%= render "categories/sidebar", categories: @categories%>
    </div>
    <div class="col-sm-9 tab-style-1-content">
      <div class="row">
        <div class="col-sm-12">
          <div class="row category-header">
            <div class="col-sm-9">
              <h2><%= t "categories.show.collection" %></h2>
            </div>
            <div class="col-sm-3">
              <%= form_with url: categories_path, method: :get,
                local: true, id: "form" do |f| %>
                <%= f.select :sort, books_sort_params,
                  {selected: params[:sort]}, {class: "form-control", id: "sort"} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <% @books.each do |book| %>
          <%= render "categories/book", book: book %>
        <% end %>
      </div>
      <div class="row">
        <div class="col-sm-9">
          <hr>
          <%= paginate @books, theme: "twitter-bootstrap-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<% provide :title, @category.title %>
<div class="container-fluid header-block">
  <h2><%= t "categories.show.category" %> </h2>
  <h1 class="text-capitalize"><%= @category.title %></h1>
</div>
<div class="container" data-turbolinks="false">
  <div class="row">
    <div class="col-sm-3">
      <%= render "categories/sidebar", categories: @categories%>
    </div>
    <div class="col-sm-9 tab-style-1-content" data-turbolinks="false">
      <div class="row">
        <div class="col-sm-12">
          <div class="row category-header">
            <div class="col-sm-9">
              <h2><%= t "categories.show.collection" %></h2>
            </div>
            <div class="col-sm-3">
              <%= form_with url: category_path(@category), method: :get,
                local: true, id: "form" do |f| %>
                <%= f.select :sort, books_sort_params,
                  {selected: params[:sort]}, {class: "form-control", id: "sort"} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <% @books.each do |book| %>
          <%= render "categories/book", book: book %>
        <% end %>
      </div>
      <div class="row">
        <div class="col-sm-9">
          <hr>
          <%= paginate @books, theme: "twitter-bootstrap-3" %>
        </div>
      </div>
    </div>
  </div>
</div>